/**
 * Demo Seed Data
 * Initial data for demo purposes
 */

import { Project, SavedStrategy, Lead } from '../../types';

export const DEMO_PROJECT: Project = {
  id: 'demo-proj-01',
  name: 'London Tech Outreach',
  description: 'Campaign targeting tech startups in London for cloud infrastructure services.',
  createdAt: new Date().toISOString(),
};

export const DEMO_STRATEGY: SavedStrategy = {
  id: 'demo-strat-01',
  projectId: 'demo-proj-01',
  createdAt: new Date().toISOString(),
  personaName: 'Founders of Tech Startups',
  searchQuery: 'Software startups London',
  rationale: 'Founders are usually the decision makers for infrastructure at early stages.',
  outreachAngle: 'Scalability and cost optimization',
  description: 'Target tech founders for cloud infrastructure solutions',
  profile: {
    productName: 'CloudScale AI',
    productDescription: 'Automated cloud scaling for high-growth startups.',
    targetAudience: 'Founders & CTOs',
    valueProposition: 'Reduce cloud costs by 40% while maintaining 99.99% uptime.',
    location: 'London, UK',
  },
};

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-001',
    projectId: 'demo-proj-01',
    leadNumber: 101,
    companyName: 'Novus FinTech',
    category: 'Software Company',
    description: 'Innovative banking solutions for the digital age.',
    address: '22 Bishopsgate',
    city: 'London',
    country: 'UK',
    coordinates: '51.5135, -0.0827',
    phone: '+44 20 7946 0123',
    email: 'james.sterling@novusfin.com',
    website: 'https://example.com/novus',
    googleMapsLink: 'https://maps.google.com',
    linkedIn: 'https://linkedin.com',
    facebook: '',
    instagram: '',
    rating: 4.8,
    reviewCount: 45,
    businessHours: 'Mon-Fri 9-6',
    qualityScore: 92,
    confidenceOverall: 0.95,
    icebreaker: "Hi James—I saw Novus recently closed their Series B and I'm a big fan of your approach to decentralized ledgers.",
    socialContext: 'LinkedIn News',
    contactName: 'James Sterling',
    contactTitle: 'CTO',
    generatedDate: new Date().toISOString().split('T')[0],
    searchCity: 'London',
    searchCountry: 'UK',
    status: 'Qualified',
    contacted: true,
    notes: 'Very interested in the automated scaling features.',
    stage: 'Qualified',
    dealValue: 12000,
    owner: 'Demo User',
    comments: [
      {
        id: 'c1',
        text: 'Had a great initial call. Sending technical specs tomorrow.',
        author: 'Demo User',
        timestamp: new Date(Date.now() - 86400000).toISOString(),
      },
    ],
  },
  {
    id: 'lead-002',
    projectId: 'demo-proj-01',
    leadNumber: 102,
    companyName: 'GreenLeaf Systems',
    category: 'Technology',
    description: 'Sustainable supply chain management software.',
    address: '154 Shoreditch High St',
    city: 'London',
    country: 'UK',
    coordinates: '51.5260, -0.0782',
    phone: '+44 20 7946 0456',
    email: 'contact@greenleaf.io',
    website: 'https://example.com/greenleaf',
    googleMapsLink: 'https://maps.google.com',
    linkedIn: '',
    facebook: '',
    instagram: '',
    rating: 4.2,
    reviewCount: 12,
    businessHours: '9-5',
    qualityScore: 78,
    confidenceOverall: 0.8,
    icebreaker: "Hi team—I came across GreenLeaf's recent blog post on supply chain transparency and loved your mission.",
    socialContext: 'Company Blog',
    contactName: 'Sarah Jenkins',
    contactTitle: 'Founder',
    generatedDate: new Date().toISOString().split('T')[0],
    searchCity: 'London',
    searchCountry: 'UK',
    status: 'New',
    contacted: false,
    notes: '',
    stage: 'New',
    dealValue: 5000,
    owner: 'Demo User',
    comments: [],
  },
  {
    id: 'lead-003',
    projectId: 'demo-proj-01',
    leadNumber: 103,
    companyName: 'Apex Architecture',
    category: 'Design Firm',
    description: 'Modern commercial architecture with a focus on tech hubs.',
    address: 'South Bank',
    city: 'London',
    country: 'UK',
    coordinates: '51.5033, -0.1195',
    phone: '+44 20 7946 0789',
    email: 'm.webb@apexarch.co.uk',
    website: 'https://example.com/apex',
    googleMapsLink: 'https://maps.google.com',
    linkedIn: '',
    facebook: '',
    instagram: '',
    rating: 5.0,
    reviewCount: 88,
    businessHours: '9-6',
    qualityScore: 85,
    confidenceOverall: 0.9,
    icebreaker: 'Hi Marcus—the Hyde Park project rendering looks incredible, really smart use of space.',
    socialContext: 'Instagram Portfolio',
    contactName: 'Marcus Webb',
    contactTitle: 'Senior Partner',
    generatedDate: new Date().toISOString().split('T')[0],
    searchCity: 'London',
    searchCountry: 'UK',
    status: 'Won',
    contacted: true,
    notes: 'Contract signed for the flagship office project.',
    stage: 'Won',
    dealValue: 25000,
    owner: 'Demo User',
    comments: [
      {
        id: 'c2',
        text: 'Signed contract! Migration starts next month.',
        author: 'Demo User',
        timestamp: new Date().toISOString(),
      },
    ],
  },
];

export const MOCK_USER = {
  name: 'Demo User',
  email: 'user@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
};
